site_name: rdrg0x
theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: deep purple
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.path
 ##   - toc.integrate
    - content.code.copy
    - search.highlight
plugins:
  - search
  - tags:
      tags_file: tags.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - toc:
      permalink: true
      
nav:
  - Home: index.md
  - Writeups:
      - HackTheBox: HackTheBox/index.md
      - TryHackme:
        - Alfred: TryHackMe/alfred/index.md
        - AD Basic Enumeration: TryHackMe/ADBasicEnum/index.md
        - Anthem: TryHackMe/anthem/index.md
        - Atlas: TryHackMe/atlas/index.md
        - Attacking kerberos: TryHackMe/attackingkerberos/index.md
        - Attacktive Directory: TryHackMe/attacktivedirectory/index.md
        - Basic Pentesting: TryHackMe/basicpentesting/index.md
        - Blaster: TryHackMe/blaster/index.md
        - Blog: TryHackMe/blog/index.md
        - Blue: TryHackMe/blue/index.md
        - Blueprint: TryHackMe/blueprint/index.md
        - Bolt: TryHackMe/bolt/index.md
        - Brainpan: TryHackMe/brainpan/index.md
        - Brainstorm: TryHackMe/brainstorm/index.md
        - Chill Hack: TryHackMe/chillhack/index.md
  - Tags: tags.md